### ISSUE TITLE
About the stroke explanation of your paper

### ISSUE THREAD

**Issue by samsara-ku** [Hxyz-123/Font-diff#12]
Hi, first I'm very pleased to your nice work.

I just want to ask some simple questions about your paper.

1. I cannot find any kind of determinant rule of chinese character decomposition. Is there any official document to explain about that? Because I'm not chinese, it is hard to find out that kind of documentations.

2. I've heard about the amount of total chinese character is ~ 100K. But in your `total_chn.txt` file, the number of character is just 6625. Because I want to know about why you just few characters, so I just search a document about [this](https://studycli.org/chinese-characters/number-of-characters-in-chinese/). Is it because most Chinese only use part of the whole character?

> In 2013, the Chinese government published a list of the 3,500 most essential characters used in modern Chinese. Chinese schoolchildren are expected to learn all 3,500 at a minimum, though many graduate knowing 5,000, 6,000 or more.

**Comment by Liangsanzhu** [comment]
I am Chinese. I believe most Chinese people only need around 6000 characters  to use in dailylife. There are many ancient and rare characters that are not commonly used.

**Comment by samsara-ku** [comment]
@Liangsanzhu First, thanks for your answer :)

So have you seen any official document about that information? I've tried to figure out that but I'm failed 😞 .

**Comment by Liangsanzhu** [comment]
http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/202103/t20210318_520473.html

**Comment by Liangsanzhu** [comment]
http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75694.html

**Comment by Liangsanzhu** [comment]
Maybe you need these documents? Besides, you can search “汉字” on http://www.moe.gov.cn/jyb_sjzl/, which is the official website of Ministry of Education of the People's Republic of China.
