### ISSUE TITLE
请教一下，测试集和训练集是如何分开的呢

### ISSUE THREAD

**Issue by zhenzi0322** [Hxyz-123/Font-diff#22]
```
data_dir: 'data/test/'
chara_nums: 6625
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
...
```
其中的`data_dir`文件夹下的结构是如何的呢？是不是类似如下：
```
data/test
   id_0
      00000.png
      ....
   id_1
     00000.png
     ...
```

**Comment by yueyuemoon** [comment]
你好，请问这个问题有办法解决了吗？困扰我好几天了，向你请教一下。

**Comment by zhenzi0322** [comment]
你是遇到啥问题了？作者没有回复你嘛

**Comment by yueyuemoon** [comment]
没有问题了，之前没理解数据集的划分，谢谢

**Comment by ArianChen777** [comment]
> 你是遇到啥问题了？作者没有回复你嘛

哥们怎么划分的，分享一下谢谢~  顺便问一下 训练了多久呢

**Comment by zhenzi0322** [comment]
> > 你是遇到啥问题了？作者没有回复你嘛
> 
> 哥们怎么划分的，分享一下谢谢~ 顺便问一下 训练了多久呢

作者文档中有写怎么划分的。你可以参考下，训练了两天，主要是看你训练多少迭代，用的显卡。显卡好的话，训练就快

**Comment by czzerone** [comment]
> > > 你是遇到啥问题了？作者没有回复你嘛
> > 
> > 
> > 哥们怎么划分的，分享一下谢谢~ 顺便问一下 训练了多久呢
> 
> 作者文档中有写怎么划分的。你可以参考下，训练了两天，主要是看你训练多少迭代，用的显卡。显卡好的话，训练就快

你好，请问下你是用了什么显卡，多少个gpu下训练了两天呀～
