### ISSUE TITLE
The generated image is incorrect

### ISSUE THREAD

**Issue by zhenzi0322** [Hxyz-123/Font-diff#23]
```
python sample.py --cfg_path cfg/test_cfg.yaml
```

![image](https://github.com/Hxyz-123/Font-diff/assets/34839719/9d28cfd2-983d-40a1-9881-02c21f26c701)

**Comment by Outlanderll** [comment]
Hello, I would like to know what is in the . /char_stroke.txt' file in test_cfg.yaml?Looking forward to your reply!

**Comment by zhenzi0322** [comment]
You can determine whether you need char_stroke.txt by reporting an error
